-- CBD-Wechselwirkungen für Schlafmittel (medication_id 52-71)

-- Z-Substanzen
INSERT INTO cbd_interactions (medication_id, interaction_type, severity, description, mechanism, recommendation, source_url) VALUES
(52, 'enhancement', 'high', 'CBD kann die sedierende Wirkung von Zopiclon verstärken und zu erhöhter Schläfrigkeit, Benommenheit und verlängerter Sedierung führen.', 'CBD hemmt CYP3A4 und CYP2C8, die für den Abbau von Zopiclon verantwortlich sind, was zu erhöhten Zopiclon-Spiegeln führt.', 'Ärztliche Beratung vor CBD-Einnahme empfohlen. Beginnen Sie mit niedrigen CBD-Dosen. Beobachten Sie verstärkte Müdigkeit, Benommenheit oder verlängerte Schläfrigkeit am nächsten Morgen.', 'https://www.drugs.com/drug-interactions/cannabidiol.html'),
(53, 'enhancement', 'high', 'CBD verstärkt die sedierende Wirkung von Zolpidem. Erhöhtes Risiko für übermäßige Schläfrigkeit, Schwindel und beeinträchtigte Koordination.', 'CBD hemmt CYP3A4 und CYP2C9, die primären Enzyme für den Zolpidem-Metabolismus, was zu erhöhten Zolpidem-Konzentrationen führt.', 'Vorsicht geboten. Dosisanpassung von Zolpidem kann erforderlich sein. Vermeiden Sie Autofahren oder gefährliche Tätigkeiten. Konsultieren Sie vor der Kombination einen Arzt.', 'https://www.drugs.com/drug-interactions/cannabidiol-with-zolpidem-3919-0-2333-0.html'),
(54, 'enhancement', 'medium', 'CBD kann die Wirkung von Zaleplon verstärken, was zu erhöhter Schläfrigkeit führen kann.', 'CBD hemmt CYP3A4, ein wichtiges Enzym für den Zaleplon-Stoffwechsel.', 'Überwachen Sie verstärkte Müdigkeitseffekte. Beginnen Sie mit niedrigen CBD-Dosen. Ärztliche Beratung empfohlen.', 'https://www.health.harvard.edu/blog/cbd-and-other-medications-proceed-with-caution-2021011121743'),

-- Benzodiazepine
(55, 'enhancement', 'high', 'CBD verstärkt die sedierende Wirkung von Diazepam deutlich. Erhöhtes Risiko für Sedierung, Atemdepression und Koordinationsstörungen.', 'CBD hemmt CYP2C19 und CYP3A4, die für den Diazepam-Abbau verantwortlich sind, was zu signifikant erhöhten Diazepam-Spiegeln führt.', 'Engmaschige ärztliche Überwachung erforderlich. Dosisreduktion von Diazepam oft notwendig. Überwachen Sie Atemdepression, excessive Sedierung und Koordinationsprobleme.', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8298645/'),
(56, 'enhancement', 'medium', 'CBD kann die sedierende Wirkung von Lorazepam verstärken.', 'Lorazepam wird hauptsächlich durch Glucuronidierung abgebaut (nicht CYP-abhängig), aber CBD kann die Gesamtsedierung durch additive Effekte erhöhen.', 'Vorsicht bei Kombination. Überwachen Sie verstärkte Schläfrigkeit und Benommenheit. Ärztliche Beratung empfohlen.', 'https://www.health.harvard.edu/blog/cbd-and-other-medications-proceed-with-caution-2021011121743'),
(57, 'enhancement', 'medium', 'CBD kann die sedierende Wirkung von Temazepam verstärken.', 'Temazepam wird durch Glucuronidierung abgebaut, aber additive sedierende Effekte mit CBD sind möglich.', 'Überwachen Sie verstärkte Müdigkeit. Beginnen Sie mit niedrigen CBD-Dosen. Konsultieren Sie Ihren Arzt.', 'https://www.mdlinx.com/article/rx-drugs-that-don%27t-mix-with-cbd-thc-and-marijuana/lfc-4695'),
(58, 'enhancement', 'high', 'CBD kann die sedierende Wirkung von Nitrazepam deutlich verstärken.', 'CBD hemmt CYP2E1 und CYP3A4, was zu erhöhten Nitrazepam-Spiegeln führt.', 'Ärztliche Überwachung erforderlich. Dosisanpassung kann notwendig sein. Achten Sie auf verlängerte Sedierung am nächsten Morgen (Hangover-Effekt).', 'https://projectcbd.org/safety/cbd-cytochrome-p450/'),
(59, 'enhancement', 'critical', 'CBD verstärkt die stark sedierende Wirkung von Flunitrazepam erheblich. Hohes Risiko für gefährliche Atemdepression und Bewusstlosigkeit.', 'CBD hemmt CYP3A4 massiv, das primäre Enzym für Flunitrazepam-Metabolismus.', 'KRITISCH: Kombination sollte vermieden werden. Falls unvermeidbar, nur unter strenger ärztlicher Aufsicht. Erhöhtes Risiko für lebensbedrohliche Atemdepression.', 'https://www.drugs.com/drug-interactions/cannabidiol.html'),
(60, 'enhancement', 'high', 'CBD verstärkt die sedierende Wirkung von Triazolam erheblich.', 'CBD hemmt CYP3A4, das primäre Enzym für Triazolam-Abbau, was zu stark erhöhten Triazolam-Konzentrationen führt.', 'Vorsicht geboten. Signifikante Dosisreduktion von Triazolam oft erforderlich. Engmaschige ärztliche Überwachung notwendig.', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8298645/'),
(61, 'enhancement', 'medium', 'CBD kann die sedierende Wirkung von Lormetazepam verstärken.', 'Lormetazepam wird durch Glucuronidierung abgebaut, aber additive sedierende Effekte sind möglich.', 'Überwachen Sie verstärkte Sedierung. Ärztliche Beratung empfohlen.', 'https://www.health.harvard.edu/blog/cbd-and-other-medications-proceed-with-caution-2021011121743'),
(62, 'enhancement', 'high', 'CBD verstärkt die sedierende Wirkung von Brotizolam.', 'CBD hemmt CYP3A4, was zu erhöhten Brotizolam-Spiegeln führt.', 'Dosisanpassung von Brotizolam kann erforderlich sein. Ärztliche Überwachung empfohlen.', 'https://projectcbd.org/safety/cbd-cytochrome-p450/'),

-- Moderne Schlafmittel
(63, 'enhancement', 'medium', 'CBD kann die Konzentration von Daridorexant erhöhen.', 'CBD hemmt CYP3A4 und CYP2C8, die für den Daridorexant-Abbau verantwortlich sind.', 'Überwachen Sie verstärkte Sedierung oder Nebenwirkungen. Dosisanpassung kann erforderlich sein.', 'https://www.mdpi.com/1424-8247/17/5/613'),
(64, 'enhancement', 'medium', 'CBD kann die Wirkung von Lemborexant verstärken.', 'CBD hemmt CYP3A4, was zu erhöhten Lemborexant-Spiegeln führen kann.', 'Beginnen Sie mit niedrigen Dosen. Überwachen Sie verstärkte Müdigkeit am nächsten Morgen.', 'https://www.neiglobal.com/default.aspx?tabname=MonthInPsychopharmPost&topic=20919'),

-- Sedierende Antidepressiva
(65, 'enhancement', 'medium', 'CBD kann die sedierende Wirkung von Mirtazapin verstärken.', 'CBD hemmt CYP2D6, CYP1A2 und CYP3A4, was zu erhöhten Mirtazapin-Spiegeln führen kann.', 'Überwachen Sie verstärkte Sedierung, Gewichtszunahme oder Mundtrockenheit. Dosisanpassung kann erforderlich sein.', 'https://www.drugs.com/drug-interactions/cannabidiol.html'),
(66, 'enhancement', 'medium', 'CBD kann die sedierende Wirkung von Trazodon verstärken.', 'CBD hemmt CYP3A4, was zu erhöhten Trazodon-Spiegeln führt.', 'Vorsicht bei Kombination. Überwachen Sie verstärkte Schläfrigkeit, Schwindel oder niedrigen Blutdruck.', 'https://projectcbd.org/safety/cbd-cytochrome-p450/'),
(67, 'enhancement', 'high', 'CBD verstärkt die sedierende Wirkung von Doxepin und erhöht das Risiko für anticholinerge Nebenwirkungen.', 'CBD hemmt CYP2D6 und CYP1A2, was zu erhöhten Doxepin-Spiegeln führt.', 'Ärztliche Überwachung empfohlen. Achten Sie auf verstärkte Müdigkeit, Mundtrockenheit, Verstopfung oder Verwirrtheit.', 'https://www.mdlinx.com/article/rx-drugs-that-don%27t-mix-with-cbd-thc-and-marijuana/lfc-4695'),

-- Antihistaminika
(68, 'enhancement', 'low', 'CBD kann die sedierende Wirkung von Diphenhydramin leicht verstärken.', 'CBD hemmt CYP2D6, was zu leicht erhöhten Diphenhydramin-Spiegeln führen kann. Additive sedierende Effekte möglich.', 'Überwachen Sie verstärkte Schläfrigkeit. Bei rezeptfreien Präparaten Vorsicht walten lassen.', 'https://www.health.harvard.edu/blog/cbd-and-other-medications-proceed-with-caution-2021011121743'),
(69, 'enhancement', 'low', 'CBD kann die sedierende Wirkung von Doxylamin leicht verstärken.', 'CBD hemmt CYP2D6. Additive sedierende Effekte sind möglich.', 'Vorsicht bei Kombination. Beginnen Sie mit niedrigen CBD-Dosen.', 'https://www.drugs.com/drug-interactions/cannabidiol.html'),

-- Melatonin
(70, 'enhancement', 'low', 'CBD kann die Wirkung von Melatonin leicht verstärken. Mögliche Synergie für besseren Schlaf.', 'CBD hemmt CYP1A2, was zu leicht erhöhten Melatonin-Spiegeln führen kann. Beide wirken schlaffördernd.', 'Kombination wird oft als gut verträglich angesehen. Kann sogar synergistische Effekte für besseren Schlaf haben. Beginnen Sie dennoch mit niedrigen Dosen.', 'https://www.healthline.com/health/cbd-and-drug-interactions-what-you-need-to-know'),

-- Pflanzliche Präparate
(71, 'enhancement', 'low', 'CBD und Baldrian können additive sedierende Effekte haben.', 'Beide wirken beruhigend und schlaffördernd. Minimale CYP-Interaktion.', 'Kombination wird oft als unbedenklich angesehen. Überwachen Sie dennoch verstärkte Müdigkeit.', 'https://www.health.harvard.edu/blog/cbd-and-other-medications-proceed-with-caution-2021011121743');
